# Azure Developer CLI project configuration for multi-agent dashboard
# Docs: https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/

name: azuredev-b20b-multiagent
metadata:
  template: custom

services:
  backend:
    project: ./Backend
    language: python
    host: appservice
    docker:
      context: ./Backend
    build:
      requirements: requirements.txt
    env_file: .env
    # Expose FastAPI on port 8000
    ingress:
      target_port: 8000
      external: true

  frontend:
    project: ./frontend
    language: js
    host: appservice
    docker:
      context: ./frontend
    build:
      app: npm install && npm run build
    env_file: .env
    ingress:
      target_port: 80
      external: true

# Environment variables and secrets are managed via .env files in each service
# You may need to adjust ports or env vars depending on your FastAPI and Vite config
